version: '3'
services:

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "4200:4200"

  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - mydata:/var/lib/postgresql/data
      - ./data:/data

volumes:
  mydata:
